pylint code audit
-- Conducted a pylint code audit

  -- Found several interesting errors, some of which were references to
     module members that didn't exist and some dead code (unused
     functions.)

  -- Normalized line lengths to 128 characters.

  -- pylint settings:

     Disabled messages and warnings: R0201,R0903,W0511,W0603,C0111

     For other settings, see .pylintrc.

-- Removed all vestiges of SublimeText2 support. Other than the fact
   that no one ever complained that it was badly broken, the time has
   come to bid ST2 a fond farewell.

-- BIG CHANGE: Get rid of all calls to (get|set)_settings(_async)?.
   Manage settings via a class, with a module-level object whose
   instance attributes are the setting.

   Before:
     Settings.get_settings_async('enable_hsdev')

   Now:
     Settings.PLUGIN.enable_hsdev

   Sure, the UPPER CASE looks ugly, but that's only because the code
   adheres to pylint's style guidelines. But it's better than worrying
   about whether the settings are being accessed from the main thread.

   Side benefit: Smaller plugin statup code in zzstartup.py. Found a
   number of places where settings were accessed, but no reasonable
   default existed.

-- Inspection: SublimeHaskell now inspects all windows, not just the active
   window.

-- hsdev.py: This has been refactored into its own module, where client,
   agent, result parsing and decorator code have their own individual
   module files. Partially done to satisfy pylint's "module too big"
   warning, but also in preparation for refactoring backend interaction.

-- Next/Prev Error: They both now work. Original code would never have
   worked as intended.

Overall, code seems a bit more stable. pylint issues that can't or won't
be fixed:

************* Module SublimeHaskell.autocomplete
I:  2, 0: Locally disabling fixme (W0511) (locally-disabled)
E:231,42: Instance of 'tuple' has no 'declarations' member (no-member)
R:239,16: Redefinition of suggestions type from list to tuple (redefined-variable-type)
E:358,23: Instance of 'tuple' has no 'get' member (no-member)

************* Module SublimeHaskell.check_lint
C:216, 4: Invalid function name "show_current_file_first_and_alter" (invalid-name)

************* Module SublimeHaskell.commands
C:  1, 0: Too many lines in module (1415/1000) (too-many-lines)
R:593,16: Redefinition of self.candidates type from list to tuple (redefined-variable-type)
R:645,20: Redefinition of candidates type from tuple to list (redefined-variable-type)
R:901, 8: Too many nested blocks (7/5) (too-many-nested-blocks)
R:932,20: Redefinition of candidates type from list to tuple (redefined-variable-type)
R:898, 4: Too many branches (19/12) (too-many-branches)
E:1128,12: Instance of 'tuple' has no 'clear' member (no-member)

************* Module SublimeHaskell.hdevtools
C: 18, 0: Invalid function name "show_hdevtools_error_and_disable" (invalid-name)
W: 85,11: Catching too general exception Exception (broad-except)

************* Module SublimeHaskell.info_popup
R: 50, 8: Too many nested blocks (6/5) (too-many-nested-blocks)

************* Module SublimeHaskell.sublime_haskell_common
C: 62, 0: Invalid function name "get_haskell_command_window_view_file_project" (invalid-name)
C: 76, 0: Invalid function name "get_cabal_project_dir_and_name_of_view" (invalid-name)
C: 97, 0: Invalid function name "get_cabal_project_dir_and_name_of_file" (invalid-name)
C:404, 4: Invalid method name "ok" (invalid-name)
C:574, 4: Invalid method name "ok" (invalid-name)

************* Module SublimeHaskell.symbols
C:236, 8: Invalid attribute name "db" (invalid-name)

************* Module SublimeHaskell.worker
W: 22,12: No exception type(s) specified (bare-except)

************* Module SublimeHaskell.hsdev.agent
C:177, 4: Invalid constant name "agent" (invalid-name)
C:179, 4: Invalid constant name "agent" (invalid-name)
C:182, 4: Invalid constant name "client" (invalid-name)
C:184, 4: Invalid constant name "client" (invalid-name)
C:187, 4: Invalid constant name "client_back" (invalid-name)
C:189, 4: Invalid constant name "client_back" (invalid-name)
E:419,12: Unexpected keyword argument 'wait' in method call (unexpected-keyword-arg)
E:419,12: Unexpected keyword argument 'on_notify' in method call (unexpected-keyword-arg)
E:430,16: Unexpected keyword argument 'on_notify' in method call (unexpected-keyword-arg)
E:430,16: Unexpected keyword argument 'wait' in method call (unexpected-keyword-arg)
E:442,12: Unexpected keyword argument 'wait' in method call (unexpected-keyword-arg)
E:442,12: Unexpected keyword argument 'on_notify' in method call (unexpected-keyword-arg)
E:454,12: Unexpected keyword argument 'wait' in method call (unexpected-keyword-arg)
E:454,12: Unexpected keyword argument 'on_notify' in method call (unexpected-keyword-arg)
E:463,12: Unexpected keyword argument 'on_notify' in method call (unexpected-keyword-arg)
E:463,12: Unexpected keyword argument 'wait' in method call (unexpected-keyword-arg)
C:491, 4: Invalid constant name "agent" (invalid-name)
C:492, 4: Invalid constant name "client" (invalid-name)
C:493, 4: Invalid constant name "client_back" (invalid-name)

************* Module SublimeHaskell.hsdev.client
C:  1, 0: Empty module docstring (empty-docstring)

************* Module SublimeHaskell.hsdev.result_parse
R: 61, 8: Redefinition of loc type from SublimeHaskell.symbols.Location to SublimeHaskell.symbols.InstalledLocation (redefined-variable-type)
R:105,12: Redefinition of retval type from SublimeHaskell.symbols.Function to SublimeHaskell.symbols.Type (redefined-variable-type)

Global evaluation
-----------------
Your code has been rated at 9.81/10